/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      container: {
        padding: "0.5rem",
        center: true,
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        "feedback-alert-1": "#cd2b31",
        "feedback-alert-2": "#fdd8d8",
        "feedback-alert-3": "#ffe5e5",
        "feedback-sucess-1": "#18794e",
        "feedback-sucess-2": "#ccebd7",
        "feedback-sucess-3": "#ddf3e4",
        "random-random-1": "#e34d8c",
        "random-random-2": "#c04277",
        "random-random-3": "#7d2a4d",
        "random-random-4": "#7000ff",
        "random-random-5": "#6200e3",
        "random-random-6": "#36007d",
        "random-random-7": "#349974",
        "random-random-8": "#2a7d5f",
        "random-random-9": "#153d2e",
        "random-random-10": "#6100ff",
        "random-random-11": "#5700e3",
        "random-random-12": "#30007d",
        "brand-brand-1": "#4529e6",
        "brand-brand-2": "#5126ea",
        "brand-brand-3": "#b0a6f0",
        "brand-brand-4": "#edeafd",
        "grey-scale-grey-0": "#0b0d0d",
        "grey-scale-grey-1": "#212529",
        "grey-scale-grey-2": "#495057",
        "grey-scale-grey-3": "#868e96",
        "grey-scale-grey-4": "#adb5bd",
        "grey-scale-grey-5": "#ced4da",
        "grey-scale-grey-6": "#dee2e6",
        "grey-scale-grey-7": "#e9ecef",
        "grey-scale-grey-8": "#f1f3f5",
        "grey-scale-grey-9": "#f8f9fa",
        "grey-scale-grey-10": "#fdfdfd",
        "colors-fixed-white-fixed": "#ffffff",
      },
    },
  },
  plugins: [],
};
